servicecomb-config-order: 10

server:
  port: 9090  # should be same with servicecomb.rest.address to use web container


APPLICATION_ID: mall-application
service_description:
  version: 0.0.2
  name: mall-gateway
#  environment: development

servicecomb:
  service:
    registry:
      address: http://localhost:30100
      instance:
        watch: false
        
  request:
    timeout: 100000
    
  rest:
    address: 0.0.0.0:9090?sslEnabled=false
    
# This is web root for windows server, change this path according to where you put your source code
gateway:
  webroot: var/static/ui
